name: "Creates a file"
description: "Creates a file and commits into the repository"

runs:
  using: "composite"
  steps:
    - name: Save custom token to a file
      shell: bash
      run: |
        date >> filename.txt
        mv filename.txt ./src/out/filename.txt

    - name: Read the file
      shell: bash
      run: |
        echo "Reading the file..."
        cat ./src/out/filename.txt
