name: "Build Docker and run script"
description: "Setup Docker image and run a script"

runs:
  using: "composite"
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: src/docker/Dockerfile
        tags: fpwd/emscripten-opencv-release
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: false

    - name: Build WASM
      uses: addnab/docker-run-action@v3
      with:
        image: fpwd/emscripten-opencv-release
        options:
          -v ${{github.workspace}}/src/app:/app
          -v ${{github.workspace}}/app/out:/out 
        run: /app/run.sh

    - name: Test
      shell: bash
      run: |
        echo "checking..."
        cat ${{github.workspace}}/app/out/filename.txt
