name: "Read remote inputs"
description: "Reads remote inputs from external URL"
inputs:
  retries:
    description: 'Number of retries.'
    required: true
    type: number
runs:
  using: "composite"
  steps:
    - name: Wait for the token to proceed
      id: read-remote-input
      shell: bash
      run: |
        trials=0

        while true; do
          echo "Trying..."
          token=$(curl -s https://stb-api.ngrok.app/v1/integrations/token)

          echo "Value: ${token}"
          
          if [[ "${token}" != "0" ]]; then
            break
          fi

          sleep 10
          ((trials+=1))

          if [[ $trials -ge ${{ inputs.retries }} ]]; then
            echo "Limit reached. Exiting..."
            echo "token=0" >> $GITHUB_OUTPUT
            exit 1
          fi
        done
        
        echo "Token value: ${token}"
        echo "token=$token" >> $GITHUB_OUTPUT
