name: Conditional Step Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Desired environment to deploy to.'
        required: true
        type: choice
        options:
          - demo

jobs:
  conditional-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            appdir:
              - 'src/app/**'

      - name: Run conditional step if changed
        if: steps.filter.outputs.appdir == 'true'
        run: echo "Files in app/ have changed."

      - name: Run conditional step if NOT changed
        if: steps.filter.outputs.appdir != 'true'
        run: echo "Files in app/ have NOT changed."