name: Conditional Step Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Desired environment to deploy to.'
        required: true
        type: choice
        options:
          - demo

jobs:
  conditional-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run conditional step
        if: contains(github.event.head_commit.message, 'app/')
        run: echo "Files in app/ have changed."