name: Deploy Demo

on:
  workflow_dispatch:
    inputs:
      with-commit:
        description: "Create a commit with the output"
        default: false
        type: boolean

jobs:
  deploy-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - uses: ./.github/actions/create-file
        with:
          with-commit: ${{ inputs.with-commit }}

      - name: Checking the file
        shell: bash
        run: cat ./src/out/filename.txt
          
