name: Docker run

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Desired environment to deploy to.'
        required: true
        type: choice
        options:
          - demo

permissions:
  id-token: write
  contents: read

concurrency:
  group: Docker run @ ${{github.ref}}
  cancel-in-progress: true
  
jobs:
  deploy-client-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      # - name: Test
      #   run: |
      #     echo ${{github.workspace}}
      #     ls -al
      #     cd ${{github.workspace}}
      #     ${{github.workspace}}/src/app/run.sh

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: src/docker/Dockerfile
          tags: fpwd/emscripten-opencv-release
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false

      - name: Build WASM
        uses: addnab/docker-run-action@v3
        with:
          image: fpwd/emscripten-opencv-release
          options:
            -v ${{github.workspace}}/src/app:/app
            -v ${{github.workspace}}/app/out:/out 
          run: /app/run.sh

      - name: Test
        run: |
          echo "checking..."
          cat ${{github.workspace}}/app/out/filename.txt
