name: Client PR Check

on:
  workflow_dispatch:
    inputs:
      with-commit:
        description: "Create a commit with the output"
        default: false
        type: boolean

  pull_request:
    branches: [ main ]
    paths:
      - src/test_subject/**

jobs:
  deploy-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: Check event name
        shell: bash
        run: |
          echo ${{ github.event_name }}
          echo ${{ inputs.with-commit || github.event_name == 'pull_request' }}

      - uses: ./.github/actions/create-file
        with:
          with-commit: ${{ inputs.with-commit || github.event_name == 'pull_request' }}
