name: Client PR Check

on:
  workflow_dispatch:
    inputs:
      with-commit:
        description: "Create a commit with the output"
        default: false
        type: boolean

  pull_request:
    branches: [ main ]
    paths:
      - src/test_subject/**

jobs:
  deploy-demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request'

      - name: Check event name
        shell: bash
        run: |
          echo ${{ github.event_name }}
          echo ${{ inputs.with-commit || github.event_name == 'pull_request' }}

      - name: Create a file action
        uses: ./.github/actions/docker-build-and-run

      - name: Commiting the file
        if: ${{ inputs.with-commit || github.event_name == 'pull_request' }}
        shell: bash
        run: |
          echo "Commiting the file..."
          git config user.name "github-actions[bot]"
          git config user.email "stb+github-actions[bot]@users.noreply.github.com"
          git add src/app/out/
          git commit -m "feat(client): [github-actions-bot] Include compiled WASM files"
          git push