name: Wait for input

on:
  workflow_dispatch:
    inputs:
      retries:
        description: 'Number of retries.'
        required: true
        type: number

jobs:
  main-job:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0
        
      - name: Print out some info
        run: |
          echo "The job was manually triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Wait for the token
        uses: ./.github/actions/read-remote-input
        with:
          retries: ${{ inputs.retries }}

      - name: Print out received token
        run: |
          echo "Token received: ${{ steps.read-remote-input.outputs.token }}."
          